### PR TITLE
Adding method validations option

### PR DESCRIPTION
**Pull request by marcotas**
This method can be optionally used instead of the property `validations` for better use with custom rules. Example usage:

```php
class CreatePhoneInteraction extends Interaction
{
    public function validations()
    {
        return [
            'phone' => ['required', new MyPhoneRule('BR')],
        ];
    }
}
```

### CODE REVIEW

**Comment by zachflower** [comment]
This is great, thanks @marcoT89! Would you mind adding a test to validate the new functionality?

**Comment by marcodevsquad** [comment]
It's done. 😉 👍

**Comment by marcodevsquad** [comment]
@zachflower where are you? I'm waiting your answer... thanks

**Review by zachflower — APPROVED** [review]
Apologies for the delay @marcoT89, this all looks great! Thank you so much for the contribution!

**Pull request merged**
